# Generated by Django 3.2.15 on 2022-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('original_title', models.CharField(default='', max_length=70)),
                ('shop', models.CharField(default='', max_length=70)),
                ('rated', models.CharField(default='', max_length=70)),
                ('launched_date', models.CharField(default='', max_length=70)),
                ('desc', models.TextField(default='', max_length=256)),
                ('img', models.TextField(default='', max_length=256)),
                ('genre', models.ManyToManyField(related_name='foods', to='foods.Genre')),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
